apiVersion: skaffold/v2beta27
kind: Config
build:
  artifacts:
  - image: ghcr.io/samcday/hcloud-fip-k8s
    docker: {}
    hooks:
      before:
      - command: [bash, build.sh]
  local:
    useDockerCLI: true
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: hcloud-fip-k8s
        chartPath: chart/
        artifactOverrides:
          image: ghcr.io/samcday/hcloud-fip-k8s
        imageStrategy:
          helm: {}
        setValues:
          floatingIP:
            selector: role=dev
            label: node-role.kubernetes.io/dev
            setupAnnotation: example.com/dev
