apiVersion: skaffold/v2beta27
kind: Config
build:
  artifacts:
  - image: samcday/the-nat-controller
    ko: {}
#    hooks:
#      before:
#      - command: [bash, build.sh]
deploy:
  helm:
    releases:
      - name: the-nat-controller
        chartPath: chart/
        artifactOverrides:
          image: samcday/the-nat-controller
        imageStrategy:
          helm: {}
