apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hcloud-fip-k8s.fullname" . }}-config
  labels:
    {{- include "hcloud-fip-k8s.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- tpl .Values.config . | nindent 4 }}
