{{ if and .Values.metrics.podMonitor (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PodMonitor")}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "hcloud-fip-k8s.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hcloud-fip-k8s.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "hcloud-fip-k8s.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
{{ end }}
